# Generated by Django 5.0.8 on 2024-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_team_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardelement',
            name='team',
        ),
        migrations.AddField(
            model_name='boardelement',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardelement',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
